---
name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt
          targets: aarch64-unknown-linux-gnu

      - name: Install the dependencies
        run: |
          sudo apt update && \
          sudo apt install -y podman binutils-aarch64-linux-gnu musl-tools && \
          cargo binstall --no-confirm cross

      - name: Linting
        run: |
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Debug builds
        run: cross build --target=aarch64-unknown-linux-musl
