---
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt
          targets: aarch64-unknown-linux-musl

      - name: Install the dependencies
        run: |
          sudo apt update && \
          sudo apt install -y podman binutils-aarch64-linux-gnu musl-tools && \
          cargo binstall --no-confirm cross

      - name: Building
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target=aarch64-unknown-linux-musl --release
          cp target/aarch64-unknown-linux-musl/release/tegratop tegratop-linux-arm64
          aarch64-linux-gnu-strip tegratop-linux-arm64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            [Release.md](${{ github.server_url }}/${{ github.repository }}/blob/master/Release.md)
          files: "tegratop*"
